//User
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING'
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED'
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED'

export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED'
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED'

//Job

export const GET_JOB_PENDING = 'GET_JOB_PENDING'
export const GET_JOB_FULFILLED = 'GET_JOB_FULFILLED'
export const GET_JOB_REJECTED = 'GET_JOB_REJECTED'

